.TH DPONG 1 "2011-08-08"
.SH NAME
dpong \- client-server D-BUS latency and stress testing tool
.SH SYNOPSIS
\fBdpong\fP \fI[<report_period>]\fP
.SH DESCRIPTION
\fIdpong\fP is the server that receives messages from \fIdping\fP.
.SH ARGUMENTS
.TP
.I report_period
Allows to change the reporting period from the default of 1000 messages.
.SH SEE ALSO
.IR dping (1)
.SH COPYRIGHT
Copyright (C) 2005-2011 Nokia Corporation.
.PP
This is free software. You may redistribute copies of it under the terms of the
GNU General Public License v2 included with the software.  There is NO
WARRANTY, to the extent permitted by law.
